import:
  - shared.filesystem

widgets:
  main-window:
    type: window
    label: "Filesystem Browser Demo"
    size: [600, 500]
    body:
      - shared.filesystem.demo:

app:
  root-widget: main-window
  main-data: filesystem
