# Simple Aggregate Demo
# All plugins in a tree-navigable interface (no docking)

import:
  - shared.imgui
  - shared.imcoolbar
  - shared.imgui-knobs
  - shared.imgui-toggle
  - shared.imspinner
  - shared.im-anim
  - shared.imguizmo
  - shared.implot
  - shared.implot3d
  - shared.imnodes
  - shared.imgui-markdown
  - shared.filesystem
  - shared.kernel
  - shared.waveform

widgets:
  main-window:
    type: imgui.window
    label: "Ymery Plugin Showcase"
    size: [1200, 800]
    body:
      - imgui.text:
          label: "Ymery Plugin Showcase"
          style:
            imgui.text: [0.9, 0.9, 0.2, 1.0]
      - imgui.separator
      - imgui.text:
          label: "Expand sections below to explore each plugin"
      - imgui.separator

      # ============================================================================
      # UI WIDGET PLUGINS
      # ============================================================================
      - imgui.collapsing-header:
          label: "UI Widget Plugins"
          flags: [default-open]
          body:
            - imgui.tree-node:
                label: "ImGui - Core Widgets"
                tooltip: "Buttons, inputs, sliders, tables, popups..."
                body:
                  - shared.imgui.demo:

            - imgui.tree-node:
                label: "ImCoolBar - Animated Toolbar"
                tooltip: "Dock-like animated toolbar"
                body:
                  - shared.imcoolbar.demo:

            - imgui.tree-node:
                label: "ImGui Knobs - Rotary Controls"
                tooltip: "Various knob styles for value adjustment"
                body:
                  - shared.imgui-knobs.demo:

            - imgui.tree-node:
                label: "ImGui Toggle - Switch Controls"
                tooltip: "Animated toggle switches"
                body:
                  - shared.imgui-toggle.demo:

            - imgui.tree-node:
                label: "ImSpinner - Loading Animations"
                tooltip: "Various spinner styles"
                body:
                  - shared.imspinner.demo:

            - imgui.tree-node:
                label: "ImAnim - Animation Engine"
                tooltip: "Tweens, springs, oscillators, easings"
                body:
                  - shared.im-anim.demo:

            - imgui.tree-node:
                label: "ImGui Markdown - Rich Text"
                tooltip: "Markdown rendering"
                body:
                  - shared.imgui-markdown.demo:

      # ============================================================================
      # 3D & PLOTTING PLUGINS
      # ============================================================================
      - imgui.collapsing-header:
          label: "3D & Plotting Plugins"
          body:
            - imgui.tree-node:
                label: "ImGuizmo - 3D Gizmos"
                tooltip: "Translation, rotation, scale gizmos"
                body:
                  - shared.imguizmo.demo:

            - imgui.tree-node:
                label: "ImPlot - 2D Plotting"
                tooltip: "Line charts, scatter plots, bar charts"
                body:
                  - shared.implot.demo:

            - imgui.tree-node:
                label: "ImPlot3D - 3D Plotting"
                tooltip: "3D surface and scatter plots"
                body:
                  - shared.implot3d.demo:

      # ============================================================================
      # NODE EDITOR PLUGINS
      # ============================================================================
      - imgui.collapsing-header:
          label: "Node Editor Plugins"
          body:
            - imgui.tree-node:
                label: "ImNodes - Visual Programming"
                tooltip: "Node-based visual programming"
                body:
                  - shared.imnodes.demo:

      # ============================================================================
      # DATA SOURCE PLUGINS
      # ============================================================================
      - imgui.collapsing-header:
          label: "Data Source Plugins"
          body:
            - imgui.tree-node:
                label: "Filesystem Browser"
                tooltip: "Tree-based filesystem navigation"
                body:
                  - shared.filesystem.demo:

            - imgui.tree-node:
                label: "Kernel Provider Hub"
                tooltip: "Central routing to data providers"
                body:
                  - shared.kernel.demo:

            - imgui.tree-node:
                label: "Waveform Visualization"
                tooltip: "Real-time waveform display"
                body:
                  - shared.waveform.demo:

app:
  root-widget: main-window
