import:
  - shared.waveform

widgets:
  main-window:
    type: imgui.window
    label: "Waveform Demo"
    size: [800, 700]
    body:
      - shared.waveform.demo:

app:
  root-widget: main-window
  data-tree: waveform
