app:
  # Local data tree for this app - demonstrates nodes editor data binding
  data:
    node-definitions:
      type: simple-data-tree
      initial:
        input-node:
          name: "Input"
          type: "Generator"
          inputs: 0
          outputs: 1
        add-node:
          name: "Add"
          type: "Generic"
          inputs: 2
          outputs: 1
        multiply-node:
          name: "Multiply"
          type: "Generic"
          inputs: 2
          outputs: 1
        condition-node:
          name: "If"
          type: "Generic"
          inputs: 1
          outputs: 2
        clamp-node:
          name: "Clamp"
          type: "Generic"
          inputs: 3
          outputs: 1
        output-node:
          name: "Output"
          type: "Generic"
          inputs: 1
          outputs: 0

    node-instances:
      type: simple-data-tree
      initial:
        inst-1:
          node-type: "input-node"
          position-x: 50
          position-y: 50
          label: "Value A"
        inst-2:
          node-type: "input-node"
          position-x: 50
          position-y: 250
          label: "Value B"
        inst-3:
          node-type: "add-node"
          position-x: 300
          position-y: 100
          label: "Sum"
        inst-4:
          node-type: "multiply-node"
          position-x: 550
          position-y: 100
          label: "Result"
        inst-5:
          node-type: "condition-node"
          position-x: 300
          position-y: 350
          label: "Check"
        inst-6:
          node-type: "clamp-node"
          position-x: 550
          position-y: 350
          label: "Limit"
        inst-7:
          node-type: "output-node"
          position-x: 800
          position-y: 150
          label: "Output"

    connections:
      type: simple-data-tree
      initial:
        wire-1:
          from: inst-1
          from-slot: 0
          to: inst-3
          to-slot: 0
        wire-2:
          from: inst-2
          from-slot: 0
          to: inst-3
          to-slot: 1
        wire-3:
          from: inst-3
          from-slot: 0
          to: inst-4
          to-slot: 0
        wire-4:
          from: inst-2
          from-slot: 0
          to: inst-4
          to-slot: 1
        wire-5:
          from: inst-4
          from-slot: 0
          to: inst-5
          to-slot: 0
        wire-6:
          from: inst-5
          from-slot: 0
          to: inst-6
          to-slot: 0
        wire-7:
          from: inst-6
          from-slot: 0
          to: inst-7
          to-slot: 0

    editor-state:
      type: simple-data-tree
      initial:
        show-grid: true
        show-tooltips: true
        zoom-level: 1.0
        pan-x: 0
        pan-y: 0
        total-connections: 7
        total-nodes: 7
        selected-node: null

  body:
    imgui.window:
      title: Nodes Editor Demo
      body:
        - imgui.tab-bar:
            body:
              # Tab 1: Interactive Nodes Editor
              - imgui.tab-item:
                  label: Nodes Editor
                  body:
                    - imgui.text:
                        content: "Advanced Nodes Editor with Connection System"
                        tooltip: "Create and manage node networks with typed connections"
                    - imgui.separator
                    - imgui.text:
                        content: "Drag nodes, connect inputs/outputs, right-click for context menu."
                    - imgui.separator
                    - nodes.nodes:
                        label: Main Editor
                        width: 900
                        height: 600
                        show-grid: true
                        node-types:
                          - name: Input
                            color: "#4CAF50"
                            inputs: 0
                            outputs: 1
                          - name: Add
                            color: "#2196F3"
                            inputs: 2
                            outputs: 1
                          - name: Multiply
                            color: "#2196F3"
                            inputs: 2
                            outputs: 1
                          - name: If
                            color: "#FF9800"
                            inputs: 1
                            outputs: 2
                          - name: Clamp
                            color: "#9C27B0"
                            inputs: 3
                            outputs: 1
                          - name: Output
                            color: "#F44336"
                            inputs: 1
                            outputs: 0
                        nodes.nodes:
                          - id: 1
                            type: Input
                            title: "Value A"
                            x: 50
                            y: 80
                          - id: 2
                            type: Input
                            title: "Value B"
                            x: 50
                            y: 280
                          - id: 3
                            type: Add
                            title: "Sum"
                            x: 280
                            y: 120
                          - id: 4
                            type: Multiply
                            title: "Product"
                            x: 500
                            y: 80
                          - id: 5
                            type: If
                            title: "Check"
                            x: 280
                            y: 320
                          - id: 6
                            type: Clamp
                            title: "Limit"
                            x: 500
                            y: 280
                          - id: 7
                            type: Output
                            title: "Result"
                            x: 720
                            y: 180
                        connections:
                          - from-node: 1
                            from-pin: 0
                            to-node: 3
                            to-pin: 0
                          - from-node: 2
                            from-pin: 0
                            to-node: 3
                            to-pin: 1
                          - from-node: 3
                            from-pin: 0
                            to-node: 4
                            to-pin: 0
                          - from-node: 2
                            from-pin: 0
                            to-node: 4
                            to-pin: 1
                          - from-node: 2
                            from-pin: 0
                            to-node: 5
                            to-pin: 0
                          - from-node: 5
                            from-pin: 0
                            to-node: 6
                            to-pin: 0
                          - from-node: 4
                            from-pin: 0
                            to-node: 7
                            to-pin: 0
                    - imgui.separator
                    - imgui.row:
                        body:
                          - imgui.button:
                              label: New Node
                              tooltip: Add a new node to the graph
                          - imgui.button:
                              label: Process
                              tooltip: Process the entire graph
                          - imgui.button:
                              label: Clear All
                              tooltip: Remove all nodes and connections
                          - imgui.button:
                              label: Center View
                              tooltip: Center the view on all nodes

              # Tab 2: Editor State
              - imgui.tab-item:
                  label: Editor State
                  body:
                    - imgui.text:
                        content: "Editor State & Statistics (Data-Bag Bound)"
                    - imgui.separator
                    - imgui.collapsing-header:
                        label: View Settings
                        body:
                          - imgui.row:
                              body:
                                - imgui.text:
                                    content: "Show Grid:"
                                - imgui.text:
                                    content: $editor-state@/show-grid
                          - imgui.row:
                              body:
                                - imgui.text:
                                    content: "Show Tooltips:"
                                - imgui.text:
                                    content: $editor-state@/show-tooltips
                          - imgui.row:
                              body:
                                - imgui.text:
                                    content: "Zoom Level:"
                                - imgui.text:
                                    content: $editor-state@/zoom-level
                          - imgui.row:
                              body:
                                - imgui.text:
                                    content: "Pan Position:"
                                - imgui.text:
                                    content: "(@pan-x, @pan-y)"

                    - imgui.collapsing-header:
                        label: Graph Statistics
                        body:
                          - imgui.row:
                              body:
                                - imgui.text:
                                    content: "Total Connections:"
                                - imgui.text:
                                    content: $editor-state@/total-connections
                          - imgui.row:
                              body:
                                - imgui.text:
                                    content: "Selected Node:"
                                - imgui.text:
                                    content: $editor-state@/selected-node

              # Tab 3: Node Types
              - imgui.tab-item:
                  label: Node Types
                  body:
                    - imgui.text:
                        content: "Available Node Types & Connector Types"
                    - imgui.separator
                    - imgui.collapsing-header:
                        label: Connection Types
                        body:
                          - imgui.text:
                              content: "Generic: Universal compatibility"
                          - imgui.text:
                              content: "Int: Integer values"
                          - imgui.text:
                              content: "Float: Floating-point values"
                          - imgui.text:
                              content: "Vector: Vector data"
                          - imgui.text:
                              content: "Image: Image data"
                          - imgui.text:
                              content: "Text: String/text data"

                    - imgui.separator
                    - imgui.collapsing-header:
                        label: Node Templates
                        body:
                          - imgui.text:
                              content: "Pre-configured node types:"
                          - imgui.separator
                          - imgui.row:
                              body:
                                - imgui.button:
                                    label: Test Node
                                    tooltip: Generic test node
                                - imgui.button:
                                    label: InputBox
                                    tooltip: Input collection node
                                - imgui.button:
                                    label: OutputBox
                                    tooltip: Output collection node
                          - imgui.separator
                          - imgui.text:
                              content: "Each node can have multiple typed inputs and outputs."
                          - imgui.text:
                              content: "Connections are validated based on type compatibility."

              # Tab 4: Advanced
              - imgui.tab-item:
                  label: Advanced
                  body:
                    - imgui.text:
                        content: "Advanced Features & Settings"
                    - imgui.separator
                    - imgui.collapsing-header:
                        label: Display Options
                        body:
                          - imgui.checkbox:
                              label: Show Grid
                              value: $editor-state@/show-grid
                              tooltip: Display background grid
                          - imgui.checkbox:
                              label: Show Tooltips
                              value: $editor-state@/show-tooltips
                              tooltip: Show hover tooltips
                          - imgui.checkbox:
                              label: Anti-Alias Curves
                              tooltip: Smooth connection curves
                          - imgui.slider-float:
                              label: Zoom Level
                              min: 0.1
                              max: 3.0
                              value: $editor-state@/zoom-level
                              tooltip: Adjust view zoom

                    - imgui.collapsing-header:
                        label: Performance
                        body:
                          - imgui.checkbox:
                              label: Enable Caching
                              tooltip: Cache node outputs
                          - imgui.checkbox:
                              label: Parallel Processing
                              tooltip: Use multiple threads
                          - imgui.slider-int:
                              label: Update Rate
                              min: 10
                              max: 60
                              tooltip: Updates per second

                    - imgui.separator
                    - imgui.collapsing-header:
                        label: File Operations
                        body:
                          - imgui.button:
                              label: Save Graph
                              tooltip: Save to JSON file
                          - imgui.button:
                              label: Load Graph
                              tooltip: Load from JSON file
                          - imgui.button:
                              label: Export Image
                              tooltip: Save as image
                          - imgui.button:
                              label: Copy Selection
                              tooltip: Copy selected nodes
