import:
  - shared.implot

widgets:
  main-window:
    type: imgui.window
    label: "ImPlot Demo"
    size: [900, 700]
    body:
      - shared.implot.demo:

app:
  root-widget: main-window
  data-tree: waveform
