app:
  body:
    window:
      title: Ymery Widget Demo
      body:
        - tab-bar:
            body:
              - tab-item:
                  label: Basic Widgets
                  body:
                    - collapsing-header:
                        label: Text & Labels
                        body:
                          - text: This is a simple text label
                          - text:
                              content: Styled text with custom content
                          - separator
                          - spacing

                    - collapsing-header:
                        label: Buttons
                        body:
                          - row:
                              body:
                                - button:
                                    label: Primary
                                - button:
                                    label: Secondary
                                - button:
                                    label: Action

                    - collapsing-header:
                        label: Input Fields
                        body:
                          - input-text:
                              label: Text Input
                              hint: Enter some text...
                          - input-int:
                              label: Integer Input
                          - separator
                          - slider-int:
                              label: Integer Slider
                              min: 0
                              max: 100
                          - slider-float:
                              label: Float Slider
                              min: 0.0
                              max: 1.0

                    - collapsing-header:
                        label: Toggles & Selection
                        body:
                          - checkbox:
                              label: Enable Feature
                          - checkbox:
                              label: Dark Mode
                          - separator
                          - combo:
                              label: Select Option
                              items:
                                - Option 1
                                - Option 2
                                - Option 3

                    - collapsing-header:
                        label: Color
                        body:
                          - color-edit:
                              label: Pick a Color

              - tab-item:
                  label: Layout Widgets
                  body:
                    - collapsing-header:
                        label: Row Layout
                        body:
                          - row:
                              body:
                                - button:
                                    label: Left
                                - button:
                                    label: Center
                                - button:
                                    label: Right

                    - collapsing-header:
                        label: Column Layout
                        body:
                          - column:
                              body:
                                - text: First item in column
                                - text: Second item in column
                                - text: Third item in column

                    - collapsing-header:
                        label: Group
                        body:
                          - group:
                              body:
                                - text: Items in a group
                                - button:
                                    label: Grouped Button

                    - collapsing-header:
                        label: Child (Scrollable Region)
                        body:
                          - child:
                              width: 0
                              height: 150
                              border: true
                              body:
                                - text: Line 1 - Scrollable content
                                - text: Line 2 - More content
                                - text: Line 3 - Even more
                                - text: Line 4 - Scroll down
                                - text: Line 5 - Keep scrolling
                                - text: Line 6 - Almost there
                                - text: Line 7 - Bottom content

              - tab-item:
                  label: Tree Widgets
                  body:
                    - tree-node:
                        label: Root Node
                        body:
                          - tree-node:
                              label: Child Node 1
                              body:
                                - text: Leaf content 1
                          - tree-node:
                              label: Child Node 2
                              body:
                                - text: Leaf content 2
                                - tree-node:
                                    label: Nested Node
                                    body:
                                      - text: Deep nested content

                    - separator

                    - collapsing-header:
                        label: Another Collapsible Section
                        body:
                          - text: This is inside a collapsing header
                          - button:
                              label: Action Button

              - tab-item:
                  label: Complex Layout
                  body:
                    - row:
                        body:
                          - column:
                              body:
                                - text: Left Panel
                                - separator
                                - input-text:
                                    label: Search
                                - checkbox:
                                    label: Filter Active
                                - button:
                                    label: Apply
                          - child:
                              width: 300
                              height: 200
                              border: true
                              body:
                                - text: Content Area
                                - separator
                                - text: This demonstrates a complex layout
                                - text: with multiple nested containers
                                - spacing
                                - row:
                                    body:
                                      - button:
                                          label: Save
                                      - button:
                                          label: Cancel

widgets:
  # Container widgets
  window:
    type: window
  column:
    type: column
  row:
    type: row
  group:
    type: group
  child:
    type: child
  tab-bar:
    type: tab-bar
  tab-item:
    type: tab-item
  tree-node:
    type: tree-node
  collapsing-header:
    type: collapsing-header

  # Basic widgets
  text:
    type: text
  button:
    type: button
  separator:
    type: separator
  spacing:
    type: spacing
  input-text:
    type: input-text
  input-int:
    type: input-int
  slider-int:
    type: slider-int
  slider-float:
    type: slider-float
  checkbox:
    type: checkbox
  combo:
    type: combo
  color-edit:
    type: color-edit
