# Docking Demo
# All plugins showcased in dockable windows

import:
  - shared.imgui
  - shared.imcoolbar
  - shared.imgui-knobs
  - shared.imgui-toggle
  - shared.imspinner
  - shared.im-anim
  - shared.imguizmo
  - shared.implot
  - shared.implot3d
  - shared.imnodes
  - shared.imgui-markdown
  - shared.filesystem
  - shared.kernel
  - shared.waveform

widgets:
  main-window:
    type: imgui.hello-imgui-main-window
    runner-params:
      app-window-params:
        window-geometry:
          size: [1800, 1000]
      imgui-window-params:
        default-imgui-window-type: provide-full-screen-dock-space
    fps-idle: 0
    body:
      # Menu
      - imgui.hello-imgui-menu:
          body:
            - imgui.menu:
                label: "File"
                body:
                  - imgui.menu-item:
                      label: "Exit"
            - imgui.menu:
                label: "View"
                body:
                  - imgui.separator-text: "UI Plugins"
                  - imgui.menu-item:
                      label: "ImGui Widgets"
                  - imgui.menu-item:
                      label: "ImCoolBar"
                  - imgui.menu-item:
                      label: "ImGui Knobs"
                  - imgui.menu-item:
                      label: "ImGui Toggle"
                  - imgui.menu-item:
                      label: "ImSpinner"
                  - imgui.menu-item:
                      label: "ImAnim"
                  - imgui.separator-text: "3D & Plotting"
                  - imgui.menu-item:
                      label: "ImGuizmo"
                  - imgui.menu-item:
                      label: "ImPlot"
                  - imgui.menu-item:
                      label: "ImPlot3D"
                  - imgui.separator-text: "Node Editors"
                  - imgui.menu-item:
                      label: "ImNodes"
                  - imgui.separator-text: "Data Sources"
                  - imgui.menu-item:
                      label: "Filesystem"
                  - imgui.menu-item:
                      label: "Kernel"
                  - imgui.menu-item:
                      label: "Waveform"

      - imgui.hello-imgui-app-menu-items:
          body:
            - imgui.menu-item:
                label: "About Ymery"

      # Docking layout
      - imgui.docking-split:
          initial-dock: "MainDockSpace"
          new-dock: "LeftPanel"
          direction: "left"
          ratio: 0.25

      # ============================================================================
      # UI WIDGET PLUGINS
      # ============================================================================
      - imgui.dockable-window:
          label: "ImGui"
          dock-space-name: "MainDockSpace"
          tooltip: "Core Dear ImGui widgets"
          body:
            - shared.imgui.demo:

      - imgui.dockable-window:
          label: "ImCoolBar"
          dock-space-name: "MainDockSpace"
          tooltip: "Animated dock-like toolbar"
          body:
            - shared.imcoolbar.demo:

      - imgui.dockable-window:
          label: "ImGui Knobs"
          dock-space-name: "MainDockSpace"
          tooltip: "Rotary control widgets"
          body:
            - shared.imgui-knobs.demo:

      - imgui.dockable-window:
          label: "ImGui Toggle"
          dock-space-name: "MainDockSpace"
          tooltip: "Animated toggle switches"
          body:
            - shared.imgui-toggle.demo:

      - imgui.dockable-window:
          label: "ImSpinner"
          dock-space-name: "MainDockSpace"
          tooltip: "Loading animations"
          body:
            - shared.imspinner.demo:

      - imgui.dockable-window:
          label: "ImAnim"
          dock-space-name: "MainDockSpace"
          tooltip: "Animation engine"
          body:
            - shared.im-anim.demo:

      - imgui.dockable-window:
          label: "Markdown"
          dock-space-name: "MainDockSpace"
          tooltip: "Markdown rendering"
          body:
            - shared.imgui-markdown.demo:

      # ============================================================================
      # 3D & PLOTTING PLUGINS
      # ============================================================================
      - imgui.dockable-window:
          label: "ImGuizmo"
          dock-space-name: "MainDockSpace"
          tooltip: "3D manipulation gizmos"
          body:
            - shared.imguizmo.demo:

      - imgui.dockable-window:
          label: "ImPlot"
          dock-space-name: "MainDockSpace"
          tooltip: "2D plotting"
          body:
            - shared.implot.demo:

      - imgui.dockable-window:
          label: "ImPlot3D"
          dock-space-name: "MainDockSpace"
          tooltip: "3D plotting"
          body:
            - shared.implot3d.demo:

      # ============================================================================
      # NODE EDITOR PLUGINS
      # ============================================================================
      - imgui.dockable-window:
          label: "ImNodes"
          dock-space-name: "MainDockSpace"
          tooltip: "Node-based visual programming"
          body:
            - shared.imnodes.demo:

      # ============================================================================
      # DATA SOURCE PLUGINS
      # ============================================================================
      - imgui.dockable-window:
          label: "Filesystem"
          dock-space-name: "LeftPanel"
          tooltip: "Filesystem browser"
          body:
            - shared.filesystem.demo:

      - imgui.dockable-window:
          label: "Kernel"
          dock-space-name: "LeftPanel"
          tooltip: "Kernel provider hub"
          body:
            - shared.kernel.demo:

      - imgui.dockable-window:
          label: "Waveform"
          dock-space-name: "MainDockSpace"
          tooltip: "Real-time waveform visualization"
          body:
            - shared.waveform.demo:

app:
  root-widget: main-window
