import:
  - shared.imgui-knobs

widgets:
  main-window:
    type: imgui.window
    label: "ImGui Knobs Demo"
    size: [700, 500]
    body:
      - shared.imgui-knobs.demo:

app:
  root-widget: main-window
