widgets:
  main-widget:
    type: docking-main-window
    title: Ymery Widget Editor
    body:
      # Menu bar - matching ymery-editor
      - main-menu-bar:
          body:
            - menu:
                label: "File"
                body:
                  - menu-item:
                      label: "New"
                  - separator: {}
                  - menu-item:
                      label: "Export YAML..."
                  - separator: {}
                  - menu-item:
                      label: "Exit"
            - menu:
                label: "Edit"
                body:
                  - menu-item:
                      label: "Clear All"
            - menu:
                label: "View"
                body:
                  - menu-item:
                      label: "Widget Browser"
                  - menu-item:
                      label: "Layout Editor"
                  - menu-item:
                      label: "Preview"

      # Docking splits - create 3 panel layout (left | center | right)
      - docking-split:
          initial-dock: "MainDockSpace"
          new-dock: "LeftPanel"
          direction: "left"
          ratio: 0.20
      - docking-split:
          initial-dock: "MainDockSpace"
          new-dock: "RightPanel"
          direction: "right"
          ratio: 0.25
      - docking-split:
          initial-dock: "RightPanel"
          new-dock: "BottomRightPanel"
          direction: "down"
          ratio: 0.50

      # Dockable windows
      - dockable-window:
          label: "Widget Browser"
          dock-space-name: "LeftPanel"
          body:
            - editor-widget-tree:
                title: ""

      - dockable-window:
          label: "Layout Editor"
          dock-space-name: "MainDockSpace"
          body:
            - editor:
                title: ""

      - dockable-window:
          label: "Preview"
          dock-space-name: "RightPanel"
          body:
            - preview:
                title: ""

      - dockable-window:
          label: "Code Preview"
          dock-space-name: "BottomRightPanel"
          body:
            - code-preview:
                title: ""

  # Widget type definitions
  docking-main-window:
    type: docking-main-window
  docking-split:
    type: docking-split
  dockable-window:
    type: dockable-window
  main-menu-bar:
    type: main-menu-bar
  menu:
    type: menu
  menu-item:
    type: menu-item
  separator:
    type: separator
  editor-widget-tree:
    type: editor-widget-tree
  editor:
    type: editor
  preview:
    type: preview
  code-preview:
    type: code-preview

app:
  widget: app.main-widget
