import:
  - shared.editor

widgets:
  main-window:
    type: docking-main-window
    title: "Ymery Layout Editor"
    body:
      # Menu bar
      - main-menu-bar:
          body:
            - menu:
                label: "File"
                body:
                  - menu-item:
                      label: "New"
                  - separator
                  - menu-item:
                      label: "Export YAML..."
                  - separator
                  - menu-item:
                      label: "Exit"
            - menu:
                label: "Edit"
                body:
                  - menu-item:
                      label: "Clear All"
            - menu:
                label: "View"
                body:
                  - menu-item:
                      label: "Widget Browser"
                  - menu-item:
                      label: "Editor"
                  - menu-item:
                      label: "Code"
                  - menu-item:
                      label: "Preview"
                  - menu-item:
                      label: "Errors"
                  - menu-item:
                      label: "Logs"

      # Docking layout
      - docking-split:
          initial-dock: "MainDockSpace"
          new-dock: "BottomPanel"
          direction: "down"
          ratio: 0.20

      - docking-split:
          initial-dock: "MainDockSpace"
          new-dock: "TopPanel"
          direction: "up"
          ratio: 0.35

      - docking-split:
          initial-dock: "TopPanel"
          new-dock: "TopLeft"
          direction: "left"
          ratio: 0.25

      - docking-split:
          initial-dock: "TopPanel"
          new-dock: "TopRight"
          direction: "right"
          ratio: 0.40

      # Upper row
      - dockable-window:
          label: "Widget Browser"
          dock-space-name: "TopLeft"
          body:
            - editor-widget-tree:

      - dockable-window:
          label: "Editor"
          dock-space-name: "TopPanel"
          body:
            - editor:

      - dockable-window:
          label: "Code"
          dock-space-name: "TopRight"
          body:
            - code-preview:

      # Middle - Preview
      - dockable-window:
          label: "Preview"
          dock-space-name: "MainDockSpace"
          body:
            - preview:

      # Bottom - Errors and Logs
      - dockable-window:
          label: "Errors"
          dock-space-name: "BottomPanel"
          body:
            - errors-view:

      - dockable-window:
          label: "Logs"
          dock-space-name: "BottomPanel"
          body:
            - logs-view:

app:
  root-widget: main-window
