widgets:
  # Widget type definitions
  imgui.window:
    type: imgui.window
  imgui.text:
    type: imgui.text
  imgui.separator:
    type: imgui.separator
  imgui.collapsing-header:
    type: imgui.collapsing-header
  hex-editor.hex-editor:
    type: hex-editor.hex-editor
  imgui.row:
    type: imgui.row

  # Main window widget
  main-window:
    type: imgui.window
    label: Hex Editor Demo
    body:
      - imgui.text:
          content: "Hex Editor Demo"
          tooltip: "Interactive hex editor widget"
      - imgui.separator
      - imgui.text:
          content: "Click on bytes to select. Use arrow keys to navigate."
      - imgui.text:
          content: "Type hex characters (0-9, A-F) to edit bytes."
      - imgui.text:
          content: "Ctrl+C to copy selected bytes to clipboard."
      - imgui.separator
      - imgui.collapsing-header:
          label: Default Hex Editor (256 bytes)
          body:
            - hex-editor.hex-editor:
                label: Default
                size: [0, 200]
      - imgui.collapsing-header:
          label: Large Buffer (1024 bytes)
          body:
            - hex-editor.hex-editor:
                label: Large
                size: [0, 300]
                buffer_size: 1024
      - imgui.collapsing-header:
          label: Read-Only Mode
          body:
            - hex-editor.hex-editor:
                label: ReadOnly
                size: [0, 150]
                buffer_size: 128
                read_only: true
      - imgui.collapsing-header:
          label: Custom Display Options
          body:
            - imgui.text:
                content: "Fixed 16 bytes per line, lowercase hex:"
            - hex-editor.hex-editor:
                label: Custom1
                size: [0, 150]
                buffer_size: 256
                bytes_per_line: 16
                lowercase: true
            - imgui.separator
            - imgui.text:
                content: "No ASCII column:"
            - hex-editor.hex-editor:
                label: NoAscii
                size: [0, 150]
                buffer_size: 128
                show_ascii: false
            - imgui.separator
            - imgui.text:
                content: "No address column:"
            - hex-editor.hex-editor:
                label: NoAddress
                size: [0, 150]
                buffer_size: 128
                show_address: false

app:
  root-widget: app.main-window
