import:
  - hello-imgui-widgets
  - data
  - widgets.basic
  - widgets.tables
  - widgets.layout
  - widgets.popups
  - widgets.trees
  - widgets.tabs
  - widgets.colors
  - widgets.combos
  - widgets.text
  - widgets.tooltips
  - widgets.selectables
  - widgets.drags
  - widgets.listboxes
  - widgets.images
  - widgets.bullets
  - examples.console
  - examples.log
  - examples.layout-example
  - examples.property-editor
  - examples.long-text
  - examples.command-palette
  - examples.drag-and-drop
  - examples.matplotlib-demo
  - examples.custom-background
  - examples.docking-demo
  - examples.implot-demo
  - examples.implot3d-demo
  - examples.markdown-demo
  - examples.node-editor-demo
  - examples.text-editor-demo
  - examples.immvision-demo
  # - examples.nanovg-demo
  - examples.imguizmo-demo
  - examples.tex-inspect-demo
  - examples.widgets-demo

widgets:
  # ============================================================================
  # MAIN WINDOW with Docking
  # ============================================================================
  main-window:
    type: hello-imgui-main-window
    runner-params:
      app-window-params:
        window-geometry:
          size: [1600, 1000]
      imgui-window-params:
        default-imgui-window-type: provide-full-screen-dock-space
    fps-idle: 0
    body:
    # Main Window Menu
    - hello-imgui-menu:
        body:
          - menu:
              label: "File"
              body:
                - menu-item:
                    label: "Open"
                - menu-item:
                    label: "Save"
                - separator:
                - menu-item:
                    label: "Exit"

          - menu:
              label: "View"
              body:
                - menu-item:
                    label: "Docking"

    - hello-imgui-app-menu-items:
        body:
          - menu-item:
              label: "About"

    # ============================================================================
    # DOCKING LAYOUT
    # ============================================================================

    # Bottom panel for logs
    - docking-split:
        initial-dock: "MainDockSpace"
        new-dock: "BottomPanel"
        direction: "down"
        ratio: 0.2

    # ============================================================================
    # MAIN PANEL - All demos tabbed
    # ============================================================================

    - dockable-window:
        label: "Intro"
        dock-space-name: "MainDockSpace"
        tooltip: "Welcome screen with introduction to this demo application."
        body:
          - text:
              label: "Welcome to Dear ImGui Bundle Demo"
              tooltip: "This demo showcases Ymery's widget system with HelloImGui docking support."
          - separator:
          - text:
              label: "This is a comprehensive demo of all ImGui Bundle features"
              tooltip: "Explore the tabs above to see different widget categories and examples."

    - dockable-window:
        label: "Dear ImGui"
        dock-space-name: "MainDockSpace"
        tooltip: "Core Dear ImGui widgets - buttons, inputs, sliders, combos, tables, popups and more."
        body:
          - menu-bar:
              body:
                - menu:
                    label: "Examples"
                    body:
                      - separator-text: "Mini apps"
                      - menu-item:
                          label: "Console"
                      - menu-item:
                          label: "Log"
                      - menu-item:
                          label: "Simple layout"
                      - menu-item:
                          label: "Property editor"
                      - separator-text: "Concepts"
                      - menu-item:
                          label: "Long text display"
                - menu:
                    label: "Tools"
                    body:
                      - menu-item:
                          label: "Metrics/Debugger"
                      - menu-item:
                          label: "Debug Log"
                      - menu-item:
                          label: "Style Editor"
                      - menu-item:
                          label: "About Dear ImGui"

          - collapsing-header:
              label: "Widgets"
              flags: [default-open]
              tooltip: "Core ImGui widgets - buttons, inputs, sliders, checkboxes, combos, and more."
              body:
                - tree-node:
                    label: "Basic"
                    flags: [default-open]
                    tooltip: "Basic widgets: buttons, inputs, sliders, checkboxes, radio buttons. Uses local data-tree for state."
                    body:
                      - widgets.basic.basic-demo:
                - tree-node:
                    label: "Tooltips"
                    tooltip: "Tooltip widgets - implicit (via 'tooltip' static) and explicit (tooltip widget with body)."
                    body:
                      - widgets.tooltips.tooltips-demo:
                - tree-node:
                    label: "Tree Nodes"
                    tooltip: "Tree-node and collapsing-header widgets for hierarchical content organization."
                    body:
                      - widgets.trees.trees-demo:
                - tree-node:
                    label: "Bullets"
                    tooltip: "Bullet-text widget for list items with bullet point prefix."
                    body:
                      - widgets.bullets.bullets-demo:
                - tree-node:
                    label: "Text"
                    tooltip: "Text display widgets - static labels, dynamic text from data binding."
                    body:
                      - widgets.text.text-demo:
                - tree-node:
                    label: "Images"
                    tooltip: "Image widgets - require texture IDs from rendering backend."
                    body:
                      - widgets.images.images-demo:
                - tree-node:
                    label: "Combo"
                    tooltip: "Combo box (dropdown) widget with static items list and data-bound selection."
                    body:
                      - widgets.combos.combos-demo:
                - tree-node:
                    label: "List Boxes"
                    tooltip: "Listbox widget - scrollable list with selectable items."
                    body:
                      - widgets.listboxes.listboxes-demo:
                - tree-node:
                    label: "Selectables"
                    tooltip: "Selectable widget - clickable text items that toggle selection state."
                    body:
                      - widgets.selectables.selectables-demo:
                - tree-node:
                    label: "Drags"
                    tooltip: "Drag widgets - drag-int and drag-float for value adjustment by dragging."
                    body:
                      - widgets.drags.drags-demo:
                - tree-node:
                    label: "Tabs"
                    tooltip: "Tab-bar and tab-item widgets for organizing content in tabbed panels."
                    body:
                      - widgets.tabs.tabs-demo:
                - tree-node:
                    label: "Colors"
                    tooltip: "Color widgets - color-edit picker and color-button display."
                    body:
                      - widgets.colors.colors-demo:

          - collapsing-header:
              label: "Layout & Scrolling"
              tooltip: "Layout widgets - child windows, columns, groups for organizing UI structure."
              body:
                - widgets.layout.layout-demo:

          - collapsing-header:
              label: "Popups & Modal windows"
              tooltip: "Popup and modal dialog widgets - overlay windows for user interaction."
              body:
                - widgets.popups.popups-demo:

          - collapsing-header:
              label: "Tables & Columns"
              tooltip: "Table widget with rows, columns, headers, and various display flags."
              body:
                - widgets.tables.tables-demo:

    - dockable-window:
        label: "Demo Apps"
        dock-space-name: "MainDockSpace"
        tooltip: "HelloImGui and ImmApp demo applications - command palette, drag and drop, custom backgrounds."
        body:
          - markdown: |
              # HelloImGui and ImmApp

              * [HelloImGui](https://pthom.github.io/hello_imgui) is a library based on ImGui that enables to easily create applications with ImGui.
              * [ImApp](https://github.com/pthom/imgui_bundle/blob/main/external/immapp/immapp/runner.h) (aka "Immediate App", a submodule of ImGuiBundle) is a thin extension of HelloImGui that enables to easily initialize the ImGuiBundle addons that require additional setup at startup.

              ## Demo applications

          - separator:

          - collapsing-header:
              label: "Command Palette"
              tooltip: "Command palette demo - searchable command interface."
              body:
                - examples.command-palette.command-palette:

          - collapsing-header:
              label: "Drag and Drop"
              tooltip: "Drag and drop demo - draggable items between containers."
              body:
                - examples.drag-and-drop.drag-and-drop:

          - collapsing-header:
              label: "Custom Background"
              tooltip: "Custom background rendering demo."
              body:
                - examples.custom-background.custom-background:

          - collapsing-header:
              label: "Docking"
              tooltip: "HelloImGui docking system demo - create flexible window layouts."
              body:
                - examples.docking-demo.docking-demo:

          - collapsing-header:
              label: "Matplotlib"
              tooltip: "Matplotlib integration demo - Python plotting in ImGui."
              body:
                - examples.matplotlib-demo.matplotlib-demo:

    - dockable-window:
        label: "Implot [3D]"
        dock-space-name: "MainDockSpace"
        tooltip: "ImPlot 2D and 3D plotting - line charts, scatter plots, bar charts, heatmaps, 3D surfaces."
        body:
          - collapsing-header:
              label: "ImPlot"
              flags: [default-open]
              tooltip: "ImPlot 2D plotting - line charts, scatter plots, bar charts, heatmaps."
              body:
                - examples.implot-demo.implot-demo:

          - collapsing-header:
              label: "ImPlot 3D"
              tooltip: "ImPlot3D - 3D surface plots and visualizations."
              body:
                - examples.implot3d-demo.implot3d-demo:

    - dockable-window:
        label: "Node Editor"
        dock-space-name: "MainDockSpace"
        tooltip: "Node editor - visual node-based programming interface. Drag nodes, connect pins."
        body:
          - text:
              label: "Node Editor Demo"
              tooltip: "Node editor - visual node-based programming interface. Drag nodes, connect pins."
          - separator:
          - examples.node-editor-demo.node-editor-demo:

    - dockable-window:
        label: "Markdown"
        dock-space-name: "MainDockSpace"
        tooltip: "Markdown rendering - format text with headers, lists, links, code blocks, and images."
        body:
          - examples.markdown-demo.markdown-demo:

    - dockable-window:
        label: "Text Editor"
        dock-space-name: "MainDockSpace"
        tooltip: "Text editor with syntax highlighting - edit code with line numbers and color themes."
        body:
          - examples.text-editor-demo.text-editor-demo:

    - dockable-window:
        label: "Widgets"
        dock-space-name: "MainDockSpace"
        tooltip: "ImGui Knobs and Spinners - additional widgets for dials, gauges, and loading animations."
        body:
          - examples.widgets-demo.widgets-demo:

    - dockable-window:
        label: "ImmVision"
        dock-space-name: "MainDockSpace"
        tooltip: "ImmVision - image visualization and inspection tools for computer vision."
        body:
          - text:
              label: "ImmVision Demo"
              tooltip: "ImmVision - image visualization and inspection tools for computer vision."
          - separator:
          - examples.immvision-demo.immvision-demo:

    - dockable-window:
        label: "ImGuizmo"
        dock-space-name: "MainDockSpace"
        tooltip: "ImGuizmo - 3D gizmos for translation, rotation, and scaling transformations."
        body:
          - text:
              label: "ImGuizmo Demo"
              tooltip: "ImGuizmo - 3D gizmos for translation, rotation, and scaling transformations."
          - separator:
          - examples.imguizmo-demo.imguizmo-demo:

    - dockable-window:
        label: "Themes"
        dock-space-name: "MainDockSpace"
        tooltip: "Theme selector - customize ImGui appearance and colors."
        body:
          - text:
              label: "Theme selector will go here"
              tooltip: "Theme selector - customize ImGui appearance and colors."

    - dockable-window:
        label: "tex_inspect"
        dock-space-name: "MainDockSpace"
        tooltip: "tex_inspect - view and analyze GPU textures in real-time."
        body:
          - text:
              label: "Texture Inspection Demo"
              tooltip: "tex_inspect - view and analyze GPU textures in real-time."
          - separator:
          - examples.tex-inspect-demo.tex-inspect-demo:

    # ============================================================================
    # BOTTOM PANEL - Logs and Errors
    # ============================================================================
    - dockable-window:
        label: "Logs"
        dock-space-name: "BottomPanel"
        tooltip: "Application log output - view spdlog messages."
        body:
          - hello-imgui-widgets.logs-view:

    - dockable-window:
        label: "Errors"
        dock-space-name: "BottomPanel"
        tooltip: "Result Errors - view error chains from failed operations."
        body:
          - hello-imgui-widgets.errors-view:


app:
  widget: app.main-window
  main-data: log-tree
