widgets:
  imgui.window:
    type: imgui.window
  imgui.text:
    type: imgui.text
  imgui.spacing:
    type: imgui.spacing
  shader-toy.shader-toy:
    type: shader-toy.shader-toy

  main-window:
    type: imgui.window
    label: Shader Toy Demo
    body:
      - imgui.text:
          content: "WebGPU Custom Shader Widget POC"
      - imgui.spacing
      - shader-toy.shader-toy:
          width: 400
          height: 300
      - imgui.spacing
      - imgui.text:
          content: "Animated shader via ImDrawList::AddCallback"

app:
  root-widget: app.main-window
