import:
  - shared.kernel

widgets:
  main-window:
    type: imgui.window
    label: "Kernel Provider Demo"
    size: [700, 600]
    body:
      - shared.kernel.demo:

app:
  root-widget: main-window
  main-data: kernel
