widgets:
  # Widget type definitions
  window:
    type: imgui.window
  text:
    type: imgui.text
  separator:
    type: imgui.separator
  node-editor:
    type: imgui-node-editor.node-editor
  node:
    type: imgui-node-editor.node
  node-pin:
    type: imgui-node-editor.node-pin

  # Main window widget
  main-window:
    type: imgui.window
    label: Node Editor Demo
    body:
      - imgui.text:
          content: "Node Editor Demo"
          tooltip: "Node graph editor for visual programming"
      - imgui.separator
      - imgui.text:
          content: "This demo showcases the node editor widget."
      - imgui.text:
          content: "Drag nodes to move them. Connect pins by dragging."
      - imgui.separator
      - node-editor:
          label: Test Editor
          size: [800, 500]

app:
  root-widget: app.main-window
